// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sczrdszbpkxzacpxhchc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjenJkc3picGt4emFjcHhoY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTQ3MDIsImV4cCI6MjA1NTk5MDcwMn0.D1YDrj-Av3tEf3stpRb-XqQuBRb8c4iltggh9W9ITHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);